spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3306/tasks
    username: root
    password: root
    
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      
server:
  port: 8084

#Eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
