    
server:
    port: 8082
spring:
    application:
        name: user-service
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/users
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      